Imagine you have a row of boxes lined up in a straight line, and each box contains a number. This line of boxes is like a 1D tensor in PyTorch.


# What is a Tensor?
A tensor is just a fancy word for a container that holds numbers. In 1D, it's like a list of numbers arranged in a single line.

# Why Use Tensors?
Tensors are useful because they allow us to handle numbers in a structured way, which is important for things like machine learning, image processing, and scientific computations.

# How is it Different from a Regular List?
While a tensor might look like a regular list of numbers, it’s optimized for performance and can handle complex operations more efficiently.
Tensors can also run on GPUs to make calculations faster.

Example of a 1D Tensor:
Imagine the numbers [2, 4, 6, 8]. In PyTorch, we could create a 1D tensor to represent this sequence:


In [2]:
import torch
tensor = torch.tensor([2, 4, 6, 8])

tensor

tensor([2, 4, 6, 8])

# What Can we Do with It?

Basic Math: We can add, subtract, multiply, or divide the numbers. 


In [4]:
print(tensor + 2) # Adds 2 to each number


tensor([ 4,  6,  8, 10])


Indexing: We can pick specific numbers from the tensor

In [6]:
print(tensor[1]) # Gets the second number

tensor(4)


Length: We can find out how many numbers are in the tensor.

In [8]:
print(len(tensor))  # Returns 4

4


# Why is it Called 1D?
The "1D" stands for one-dimensional, meaning the numbers are arranged in a single line. If it were 2D, the numbers would be arranged in rows and columns, like a grid.

In short, a 1D tensor is like a supercharged list of numbers, designed to handle data efficiently and perform calculations quickly, especially when dealing with lots of numbers.

In [10]:
## importing the required libraries

import torch 
import numpy as np 
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline  

In [11]:
## checking the version of pytorch

torch.__version__

'2.5.0.dev20240808'

In [12]:
### function for plotting the vectors in co-ordinate system.

# @param: Vectors = [{"vector": vector variable, "name": name of vector, "color": color of the vector on diagram}]
    
def plotVec(vectors):
    ax = plt.axes()
    
    # For loop to draw the vectors
    for vec in vectors:
        ax.arrow(0, 0, *vec["vector"], head_width = 0.05,color = vec["color"], head_length = 0.1)
        plt.text(*(vec["vector"] + 0.1), vec["name"])
    
    plt.ylim(-2,2)
    plt.xlim(-2,2)

# Tensor Datatypes

# Convert integer to tensor

In [15]:
# Convert a integer list with length 5 to a tensor

ints_to_tensor = torch.tensor([0, 1, 2, 3, 4])
print("The dtype of tensor object after converting it to tensor: ", ints_to_tensor.dtype)
print("The type of tensor object after converting it to tensor: ", ints_to_tensor.type())

## As a result, the integer list has been converted to a long tensor.

The dtype of tensor object after converting it to tensor:  torch.int64
The type of tensor object after converting it to tensor:  torch.LongTensor


In [16]:
type(ints_to_tensor)

torch.Tensor

# Convert float to tensor

In [18]:
# Convert a float list with length 5 to a tensor

floats_to_tensor = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0])
print("The dtype of tensor object after converting it to tensor: ", floats_to_tensor.dtype)
print("The type of tensor object after converting it to tensor: ", floats_to_tensor.type())

The dtype of tensor object after converting it to tensor:  torch.float32
The type of tensor object after converting it to tensor:  torch.FloatTensor


In [19]:
list_floats=[0.0, 1.0, 2.0, 3.0, 4.0]

floats_int_tensor=torch.tensor(list_floats,dtype=torch.int64)

print("The dtype of tensor object is: ", floats_int_tensor.dtype)
print("The type of tensor object is: ", floats_int_tensor.type())

# The elements in the list that will be converted to tensor must have the same type.

The dtype of tensor object is:  torch.int64
The type of tensor object is:  torch.LongTensor


# Convert integer to float tensor

In [21]:
# Convert a integer list with length 5 to float tensor

new_float_tensor = torch.FloatTensor([0, 1, 2, 3, 4])
new_float_tensor.type()
print("The type of the new_float_tensor:", new_float_tensor.type())

The type of the new_float_tensor: torch.FloatTensor


In [22]:
new_float_tensor = torch.FloatTensor([0, 1, 2, 3, 4])
new_float_tensor

tensor([0., 1., 2., 3., 4.])

In [23]:
# Another method to convert the integer list to float tensor

old_int_tensor = torch.tensor([0, 1, 2, 3, 4])
new_float_tensor = old_int_tensor.type(torch.FloatTensor)
print("The type of the new_float_tensor:", new_float_tensor.type())

The type of the new_float_tensor: torch.FloatTensor


In [24]:
# Using the tensor_obj.size() & tensor_ndimension.size() methods

print("The size of the new_float_tensor: ", new_float_tensor.size())
print("The dimension of the new_float_tensor: ",new_float_tensor.ndimension())

The size of the new_float_tensor:  torch.Size([5])
The dimension of the new_float_tensor:  1


# What is tensor.size()?
Think of a tensor as a collection of numbers arranged in a certain shape. The size() method tells you how many numbers are in each "row," "column," or "dimension" of the tensor.

For a 1D tensor (a single line of numbers, like [3, 5, 7]), size() will tell you how many numbers are in that line.


In [26]:
import torch
tensor = torch.tensor([3, 5, 7])
print(tensor.size()) 

torch.Size([3])


# What is tensor.ndimension()?
The ndimension() method tells you how many dimensions (or levels of arrangement) the tensor has.

A 1D tensor has 1 dimension because the numbers are arranged in a straight line.


In [28]:
print(tensor.ndimension())


1


# Summary:
* tensor.size(): Tells us the shape or size of the tensor in each dimension.
* tensor.ndimension(): Tells us how many dimensions the tensor has (1D, 2D, 3D, etc.).

## In short
> size(): "How big is this in each direction?"

> ndimension(): "How many directions (dimensions) are there?"

# What is view()?
The view() method in PyTorch is used to reshape a tensor without changing the data inside it. Think of it as reorganizing the same set of numbers into a different arrangement.

# Why Use view()?
Imagine you have a box of chocolates arranged in a single line (1D), but you want to organize them into a grid (2D) to make them easier to see or work with. The view() method helps you do that.


In [31]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor

tensor([1, 2, 3, 4, 5, 6])

# Reshape with view():

reshaping this into a grid with 2 rows and 3 columns:

In [33]:
reshaped = tensor.view(2, 3)
print(reshaped)


tensor([[1, 2, 3],
        [4, 5, 6]])


# Key Points to Remember:
1. The Total Number of Elements Must Stay the Same:
You can only reshape the tensor if the total number of elements remains unchanged.

Example:
* Original tensor: 6 elements ([1, 2, 3, 4, 5, 6]).
* New shape: 2 rows × 3 columns = 6 elements.
* If the numbers don’t match, you’ll get an error.

2. Use -1 to Let PyTorch Calculate Automatically:
If you know one dimension but not the other, you can use -1, and PyTorch will figure out the missing size.

3. It Doesn’t Change the Original Tensor:
The view() method creates a new tensor with the new shape. The original tensor remains unchanged unless you overwrite it.

# When to Use view()?
1. Reshaping Data for Computations:
Machine learning models often expect data in a specific shape. view() helps you prepare the data.

2. Organizing Numbers for Easier Understanding:
It’s easier to understand a grid of numbers than a long list in some cases.

In [35]:
# Use -1 to Let PyTorch Calculate automatically 

tensor = torch.tensor([1, 2, 3, 4, 5, 6])
reshaped = tensor.view(-1, 2)  # Automatically calculates rows
print(reshaped)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [36]:
## reshaping to different shape
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
reshaped = tensor.view(3, 2)
print(reshaped)


tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [37]:
## Introducing the tensor_obj.view(row, column) method

twoD_float_tensor = new_float_tensor.view(5, 1)
print("Original Size: ", new_float_tensor.size())
print("Size after view method", twoD_float_tensor.size())

Original Size:  torch.Size([5])
Size after view method torch.Size([5, 1])


# Convert a numpy array to a tensor

In [39]:
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0])
new_tensor = torch.from_numpy(numpy_array)

print("The dtype of new tensor: ", new_tensor.dtype)
print("The type of new tensor: ", new_tensor.type())

The dtype of new tensor:  torch.float64
The type of new tensor:  torch.DoubleTensor


# Convert a tensor to a numpy array

In [41]:
back_to_numpy = new_tensor.numpy()
print("The numpy array from tensor: ", back_to_numpy)
print("The dtype of numpy array: ", back_to_numpy.dtype)

The numpy array from tensor:  [0. 1. 2. 3. 4.]
The dtype of numpy array:  float64


# Convert a panda series to a tensor

In [43]:
pandas_series=pd.Series([0.1, 2, 0.3, 10.1])
new_tensor=torch.from_numpy(pandas_series.values)
print("The new tensor from numpy array: ", new_tensor)
print("The dtype of new tensor: ", new_tensor.dtype)
print("The type of new tensor: ", new_tensor.type())

The new tensor from numpy array:  tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)
The dtype of new tensor:  torch.float64
The type of new tensor:  torch.DoubleTensor


In [44]:
# Set all elements in numpy array to zero 
numpy_array[:] = 0
print("The new tensor points to numpy_array : ", new_tensor)
print("and back to numpy array points to the tensor: ", back_to_numpy)

The new tensor points to numpy_array :  tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)
and back to numpy array points to the tensor:  [0. 0. 0. 0. 0.]


# What is item()?
The item() method is used to extract a single number (a Python scalar) from a tensor that contains only one value.

# Why Use item()?
Sometimes, after performing calculations, you end up with a tensor that has just one number inside it. The item() method is like saying:

> "Give me just the number, not the tensor."


In [46]:
# Single-Value Tensor:

import torch
tensor = torch.tensor([42])
tensor

tensor([42])

## extract with item()
number = tensor.item()
print(number)


# When Should we Use item()?
1. For Single-Value Tensors:
If a tensor has only one value, item() extracts it as a plain number.

2. After Calculations:
Many operations in PyTorch (like finding the maximum or minimum) can return a tensor with a single value. Use item() to get the number.

3. When You Need a Plain Python Number:
Sometimes, we need the number to use it with other Python functions or libraries that don’t work with tensors.

In [49]:
tensor = torch.tensor(3.14)  # A tensor with one value
print(tensor.item())


3.140000104904175


In [50]:
result = torch.tensor([10]).max()  # Result is a tensor with one value
print(result.item()) 

10


# Key Points to Remember:
1. It Only Works for Single-Value Tensors:
If the tensor has more than one value, you’ll get an error.

2. What Does It Return?
* If the tensor holds an integer, item() returns a Python int.
* If the tensor holds a decimal, item() returns a Python float.




In [52]:
## tensor = torch.tensor([1, 2, 3])
## print(tensor.item())  # Error: ValueError
"""---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[82], line 2
      1 tensor = torch.tensor([1, 2, 3])
----> 2 print(tensor.item())

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar """

'---------------------------------------------------------------------------\nRuntimeError                              Traceback (most recent call last)\nCell In[82], line 2\n      1 tensor = torch.tensor([1, 2, 3])\n----> 2 print(tensor.item())\n\nRuntimeError: a Tensor with 3 elements cannot be converted to Scalar '

In [53]:
this_tensor=torch.tensor([0,1, 2,3]) 

print("the first item is given by",this_tensor[0].item(),"the first tensor value is given by ",this_tensor[0])
print("the second item is given by",this_tensor[1].item(),"the second tensor value is given by ",this_tensor[1])
print("the third  item is given by",this_tensor[2].item(),"the third tensor value is given by ",this_tensor[2])

the first item is given by 0 the first tensor value is given by  tensor(0)
the second item is given by 1 the second tensor value is given by  tensor(1)
the third  item is given by 2 the third tensor value is given by  tensor(2)


# What is tolist()?
The tolist() method is used to convert a PyTorch tensor into a regular Python list.

Think of it as taking the numbers from the tensor and putting them into a plain Python list that we can use in other Python functions or programs.

# Why Use tolist()?
Tensors are great for mathematical computations, but sometimes we need the data in a simpler format, like a Python list, to:

1. Work with Python libraries that don’t support tensors.
2. Print or display the data in a familiar way.
3. Perform operations that are easier to do with lists.




# Converting a 1D Tensor to a List

In [56]:
import torch
tensor = torch.tensor([1, 2, 3, 4])
python_list = tensor.tolist()
print(python_list)


[1, 2, 3, 4]


In [57]:
torch_to_list=this_tensor.tolist()

print('tensor:', this_tensor,"\nlist:",torch_to_list)

tensor: tensor([0, 1, 2, 3]) 
list: [0, 1, 2, 3]


# Key Points to Remember:
1. Works for Any Tensor Shape:
Whether it’s a 1D, 2D, or multi-dimensional tensor, tolist() converts it to the equivalent nested list.

2. Data Type Conversion:
The numbers in the tensor are converted to Python’s native data types:
* Integers (int) for whole numbers.
* Floats (float) for decimal numbers.

3. It Doesn’t Change the Original Tensor:
The tolist() method creates a new list. The tensor itself remains unchanged.

# When Should we Use tolist()?
1. To Work with Python Functions or Libraries:
Some Python libraries (like matplotlib for plotting) work better with lists than tensors.

2. To Debug or Print Data:
If we want to see our tensor data in a simple and readable format, convert it to a list.

3. For Simpler Operations:

If we’re doing basic tasks like looping through numbers, a list is often easier to work with than a tensor.


# What is Indexing and Slicing?
Think of a PyTorch tensor as a collection of numbers arranged in a specific shape, like a row, grid, or even a stack of grids.

* Indexing is like pointing to a specific box in the collection and saying, “I want this one.”
* Slicing is like selecting a group of boxes and saying, “I want these ones.”

# Why Use Indexing and Slicing?
When working with tensors, we often don’t need all the data at once. we might want to:
1. Pick a specific number.
2. Extract a row, column, or smaller section of the tensor.
3. Rearrange or manipulate parts of the data.



In [60]:
tensor = torch.tensor([10, 20, 30, 40])
print(tensor[1])  


tensor(20)


In [61]:
tensor = torch.tensor([10, 20, 30, 40])
print(tensor[1:3]) 


tensor([20, 30])


In [62]:
## Advanced slicing, where we skip the steps
tensor = torch.tensor([10, 20, 30, 40, 50])
print(tensor[::2]) 


tensor([10, 30, 50])


# Key Points to Remember:
1. Indexing Starts at 0:
The first element is at index 0, not 1.

2. Ranges Exclude the End:
In slicing, the range start:end includes start but excludes end.

3. Use : for All Rows or Columns:
* The : means “select everything in this dimension.”

4. Works for Any Dimension:

Indexing and slicing work the same way for 1D, 2D, or higher-dimensional tensors.


In [64]:
# A tensor for showing how the indexs work on tensors

index_tensor = torch.tensor([0, 1, 2, 3, 4])
print("The value on index 0:",index_tensor[0])
print("The value on index 1:",index_tensor[1])
print("The value on index 2:",index_tensor[2])
print("The value on index 3:",index_tensor[3])
print("The value on index 4:",index_tensor[4])

The value on index 0: tensor(0)
The value on index 1: tensor(1)
The value on index 2: tensor(2)
The value on index 3: tensor(3)
The value on index 4: tensor(4)


In [65]:
# A tensor for showing how to change value according to the index

tensor_sample = torch.tensor([20, 1, 2, 3, 4])
tensor_sample

tensor([20,  1,  2,  3,  4])

In [66]:
# Change the value on the index 0 to 100

print("Inital value on index 0:", tensor_sample[0])
tensor_sample[0] = 100
print("Modified tensor:", tensor_sample)

Inital value on index 0: tensor(20)
Modified tensor: tensor([100,   1,   2,   3,   4])


In [67]:
# Change the value on the index 4 to 0

print("Inital value on index 4:", tensor_sample[4])
tensor_sample[4] = 0
print("Modified tensor:", tensor_sample)

Inital value on index 4: tensor(4)
Modified tensor: tensor([100,   1,   2,   3,   0])


In [68]:
# Slice tensor_sample

subset_tensor_sample = tensor_sample[1:4]
print("Original tensor sample: ", tensor_sample)
print("The subset of tensor sample:", subset_tensor_sample)

Original tensor sample:  tensor([100,   1,   2,   3,   0])
The subset of tensor sample: tensor([1, 2, 3])


In [69]:
# Change the values on index 3 and index 4

print("Inital value on index 3 and index 4:", tensor_sample[3:5])
tensor_sample[3:5] = torch.tensor([300.0, 400.0])
print("Modified tensor:", tensor_sample)

Inital value on index 3 and index 4: tensor([3, 0])
Modified tensor: tensor([100,   1,   2, 300, 400])


In [70]:
# Using variable to contain the selected index, and pass it to slice operation

selected_indexes = [3, 4]
subset_tensor_sample = tensor_sample[selected_indexes]
print("The inital tensor_sample", tensor_sample)
print("The subset of tensor_sample with the values on index 3 and 4: ", subset_tensor_sample)

The inital tensor_sample tensor([100,   1,   2, 300, 400])
The subset of tensor_sample with the values on index 3 and 4:  tensor([300, 400])


In [71]:
#Using variable to assign the value to the selected indexes

print("The inital tensor_sample", tensor_sample)
selected_indexes = [1, 3]
tensor_sample[selected_indexes] = 100000
print("Modified tensor with one value: ", tensor_sample)

The inital tensor_sample tensor([100,   1,   2, 300, 400])
Modified tensor with one value:  tensor([   100, 100000,      2, 100000,    400])


# Tensor Functions

# What Are Tensor Functions?
Tensor functions are like tools or commands that we can use to work with tensors. They help us in:
1. Perform calculations (like addition or multiplication).
2. Change the shape of tensors.
3. Extract information (like the maximum value or the size).
4. Transform tensors (like sorting or normalizing).

Think of tensor functions as a toolbox that makes working with tensors easier and more efficient.

# Why Are Tensor Functions Important?
Tensors are used to represent data in PyTorch. To work with this data, you need ways to manipulate, analyze, and process it. Tensor functions let you do this without writing complex code from scratch.



# Statistical Functions

# Find Max Value


In [75]:
max_value = tensor.max()
print(max_value)


tensor(50)


# Find Min Value

In [77]:
min_value = tensor.min()
print(min_value)  


tensor(10)


# Find Mean Value

In [79]:
mean_value = tensor.float().mean()
print(mean_value)  # Output: 2.5


tensor(30.)


In [80]:
# Sample tensor for mathmatic calculation methods on tensor

math_tensor = torch.tensor([1.0, -1.0, 1, -1])
print("Tensor example: ", math_tensor)

Tensor example:  tensor([ 1., -1.,  1., -1.])


In [81]:
#Calculate the mean for math_tensor

mean = math_tensor.mean()
print("The mean of math_tensor: ", mean)

The mean of math_tensor:  tensor(0.)


# Find Standard Deviation

In [83]:
#Calculate the standard deviation for math_tensor

standard_deviation = math_tensor.std()
print("The standard deviation of math_tensor: ", standard_deviation)

The standard deviation of math_tensor:  tensor(1.1547)


In [84]:
# Sample for introducing max and min methods

max_min_tensor = torch.tensor([1, 1, 3, 5, 5])
print("Tensor example: ", max_min_tensor)

Tensor example:  tensor([1, 1, 3, 5, 5])


In [85]:
# Method for finding the maximum value in the tensor

max_val = max_min_tensor.max()
print("Maximum number in the tensor: ", max_val)

Maximum number in the tensor:  tensor(5)


In [86]:
 max_min_tensor.max()

tensor(5)

In [87]:
# Method for finding the minimum value in the tensor

min_val = max_min_tensor.min()
print("Minimum number in the tensor: ", min_val)

Minimum number in the tensor:  tensor(1)


In [88]:
max_min_tensor.min()

tensor(1)

# Find Sin

# Method for calculating the sin result of each element in the tensor

pi_tensor = torch.tensor([0, np.pi/2, np.pi])
sin = torch.sin(pi_tensor)
print("The sin result of pi_tensor: ", sin)

# Tensor Operations

# Tensor Addition

In [92]:
# Create two sample tensors

u = torch.tensor([1, 0])
v = torch.tensor([0, 1])
w = u+v
w

tensor([1, 1])

In [93]:
# tensor + scalar

u = torch.tensor([1, 2, 3, -1])
v = u + 1
print ("Addition Result: ", v)

Addition Result:  tensor([2, 3, 4, 0])


# Tensor Subtraction


In [95]:
u = torch.tensor([1, 0])
v = torch.tensor([0, 1])
w = u - v 
w

tensor([ 1, -1])

# Tensor Multiplication



In [97]:
# tensor * scalar

u = torch.tensor([1, 2])
v = 2 * u
print("The result of 2 * u: ", v)

The result of 2 * u:  tensor([2, 4])


In [98]:
# tensor * tensor

u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
w = u * v
print ("The result of u * v", w)

The result of u * v tensor([3, 4])


# Dot Product 

In [100]:
# Calculate dot product of u, v

u = torch.tensor([1, 2])
v = torch.tensor([3, 2])

print("Dot Product of u, v:", torch.dot(u,v))

Dot Product of u, v: tensor(7)


# What is torch.linspace()?
The torch.linspace() function is used to create a tensor that contains numbers evenly spaced between two specified values.

Think of it as drawing a straight line between two points and marking equal intervals along that line. Each mark becomes a number in the tensor.

# Why Use torch.linspace()?
* When we need a set of evenly spaced numbers for calculations or visualizations.
* When we want to divide a range into smaller parts, like creating a timeline or sampling points.


In [102]:
# First try on using linspace to create tensor

len_5_tensor = torch.linspace(-2, 2, steps = 5)
print ("First Try on linspace", len_5_tensor)

First Try on linspace tensor([-2., -1.,  0.,  1.,  2.])


In [103]:
# Second try on using linspace to create tensor

len_9_tensor = torch.linspace(-2, 2, steps = 9)
print ("Second Try on linspace", len_9_tensor)

Second Try on linspace tensor([-2.0000, -1.5000, -1.0000, -0.5000,  0.0000,  0.5000,  1.0000,  1.5000,
         2.0000])


In [104]:
# Construct the tensor within 0 to 360 degree

pi_tensor = torch.linspace(0, 2*np.pi, 100)
sin_result = torch.sin(pi_tensor)

In [105]:
# Plot sin_result

plt.plot(pi_tensor.numpy(), sin_result.numpy())